// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCWy4u5kaTXE0b_N20II69Iu4FYxjFIc4s',
    appId: '1:298287723199:web:13fda5b478e1c2aa250c0a',
    messagingSenderId: '298287723199',
    projectId: 'o6uattendance',
    authDomain: 'o6uattendance.firebaseapp.com',
    storageBucket: 'o6uattendance.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABiOUiQq8iCciXlAPBIvRySi-NZRVhYP4',
    appId: '1:298287723199:android:9f3adae4d2a66705250c0a',
    messagingSenderId: '298287723199',
    projectId: 'o6uattendance',
    storageBucket: 'o6uattendance.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGIB5T1uyAcOaiB2SL1TYDlZo8dMEH7ds',
    appId: '1:298287723199:ios:56d06956868fbfe7250c0a',
    messagingSenderId: '298287723199',
    projectId: 'o6uattendance',
    storageBucket: 'o6uattendance.appspot.com',
    iosBundleId: 'com.onepexil.o6uattendance.o6uAttendancePharmacy',
  );
}
